import { VehicleType } from '@/types';

export const VEHICLE_TYPES: VehicleType[] = [
  {
    id: 'economy',
    category: 'economy',
    name: 'Economy',
    description: 'Affordable rides for everyday travel',
    image: '/images/vehicles/economy.png',
    passengers: 4,
    luggage: 2,
    eta: 3,
    pricePerKm: 0.6,
    basePrice: 3,
    minPrice: 5,
  },
  {
    id: 'comfort',
    category: 'comfort',
    name: 'Comfort',
    description: 'Newer cars with extra legroom',
    image: '/images/vehicles/comfort.png',
    passengers: 4,
    luggage: 2,
    eta: 5,
    pricePerKm: 0.9,
    basePrice: 5,
    minPrice: 8,
  },
  {
    id: 'business',
    category: 'business',
    name: 'Business',
    description: 'Premium sedans for business travel',
    image: '/images/vehicles/business.png',
    passengers: 3,
    luggage: 2,
    eta: 7,
    pricePerKm: 1.4,
    basePrice: 8,
    minPrice: 15,
  },
  {
    id: 'suv',
    category: 'suv',
    name: 'SUV',
    description: 'Spacious SUVs for groups',
    image: '/images/vehicles/suv.png',
    passengers: 6,
    luggage: 4,
    eta: 8,
    pricePerKm: 1.2,
    basePrice: 7,
    minPrice: 12,
  },
  {
    id: 'minivan',
    category: 'minivan',
    name: 'Minivan',
    description: 'Perfect for families and groups',
    image: '/images/vehicles/minivan.png',
    passengers: 7,
    luggage: 5,
    eta: 10,
    pricePerKm: 1.1,
    basePrice: 8,
    minPrice: 15,
  },
  {
    id: 'minibus',
    category: 'minibus',
    name: 'Minibus',
    description: 'Group travel up to 16 passengers',
    image: '/images/vehicles/minibus.png',
    passengers: 16,
    luggage: 10,
    eta: 15,
    pricePerKm: 1.8,
    basePrice: 20,
    minPrice: 30,
  },
  {
    id: 'bus',
    category: 'bus',
    name: 'Bus',
    description: 'Large group transportation',
    image: '/images/vehicles/bus.png',
    passengers: 50,
    luggage: 30,
    eta: 20,
    pricePerKm: 2.5,
    basePrice: 50,
    minPrice: 80,
  },
  {
    id: 'airport',
    category: 'airport',
    name: 'Airport Transfer',
    description: 'Reliable airport pickup & dropoff',
    image: '/images/vehicles/airport.png',
    passengers: 4,
    luggage: 3,
    eta: 5,
    pricePerKm: 1.0,
    basePrice: 15,
    minPrice: 20,
  },
  {
    id: 'corporate',
    category: 'corporate',
    name: 'Corporate Transfer',
    description: 'Executive chauffeur service',
    image: '/images/vehicles/corporate.png',
    passengers: 3,
    luggage: 2,
    eta: 10,
    pricePerKm: 1.6,
    basePrice: 12,
    minPrice: 25,
  },
];

export const GLOBAL_PRICING_MULTIPLIER = 1.2; // market price + 20%

export const AIRPORT_FIXED_PRICES: Record<string, number> = {
  'baku-airport-city': 25,
  'baku-airport-seaside': 30,
  'baku-airport-suburban': 40,
};

export const CURRENCY = 'AZN';
